name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: "Setup Passbolt"
        run: |
            git clone https://github.com/passbolt/passbolt_docker.git ../passbolt_docker
            cd ../passbolt_docker
            docker-compose up -d -f docker-compose/docker-compose-ce.yaml
            docker ps -a
      - name: "Test"
        run: |
            docker exec passbolt_docker_passbolt_1 sh -c '/usr/bin/wait-for.sh -t 30 localhost:443'
            output=$(docker exec passbolt_docker_passbolt_1 sh -c 'su -m -c "/usr/share/php/passbolt/bin/cake \
              passbolt register_user \
              -u your@email.com \
              -f yourname \
              -l surname \
              -r admin" -s /bin/sh www-data')
            export REG_URL=$(echo ${output##* your mailbox or here: } | tr -d '\n')
            echo "Register with $REG_URL"
            go test -v ./...
